// ============================================================================
// MODULE: vigil80_spi_receiver_16to8
// DESCRIPTION:
// Receives VIGIL80 SPI video stream.
//
// VIGIL80 is SPI master:
// - video_sck  generated by camera
// - video_csb  active low, one chip select per frame
// - video_mosi data from camera to FPGA
//
// The first FRAME_PIX words are active image pixels.
// Footer words are discarded.
//
// Each input pixel is 16-bit thermal data.
// Output pixel is 8-bit grayscale.
// ============================================================================

module vigil80_spi_receiver_16to8 #(
    parameter int FRAME_PIX    = 6400,
    parameter int FOOTER_WORDS = 23,
    parameter int TOTAL_WORDS  = FRAME_PIX + FOOTER_WORDS,
    parameter int ADDR_BITS    = $clog2(FRAME_PIX),

    parameter int TEMP_MIN     = 16'd27315,   //Minimum thermal value used as reference for the conversion
    parameter int TEMP_SHIFT   = 5
)(
    input  logic rst_n,

    input  logic video_sck,   //clock camera IR (4.6 Mbits/s)
    input  logic video_csb,   //chip select active low
    input  logic video_mosi,  //data

    input  logic wr_allow,  //(1: save frame; 0: discard frame)

    output logic pix_valid,    //high when conversion 16 to 8 bit is completed
    output logic [ADDR_BITS-1:0] pix_addr,
    output logic [7:0] pix_data,
    output logic frame_done    //high when the full frame (6400+23 words) is received and must be saved in memory
);

    localparam int WORD_CNT_BITS = $clog2(TOTAL_WORDS);

    logic [15:0] shift_reg_current_word;  //shift register to build up the 16 bits word
    logic [3:0]  bit_cnt;                 //to count from 0 to 15

    logic [WORD_CNT_BITS-1:0] word_cnt;   //Count how many 16-bit words have been received in the current frame

    logic frame_active;       // high while CS frame reception is active
    logic capture_enable;     //useful for preventing wr_allow change while saving 

    // =========================================================================
    // 16-bit thermal value to 8-bit grayscale conversion
    //
    // gray = clamp((thermal - TEMP_MIN) >> TEMP_SHIFT)
    //
    // TEMP_MIN and TEMP_SHIFT can be tuned to improve image contrast.
    // =========================================================================

    function automatic logic [7:0] thermal16_to_gray8(input logic [15:0] thermal);  
        logic [15:0] diff;
        logic [15:0] scaled;
        begin
            if (thermal <= TEMP_MIN) begin
                thermal16_to_gray8 = 8'd0;  //Anything < 0 °C is displayed as black
            end 
            else begin
                diff   = thermal - TEMP_MIN;
                scaled = diff >> TEMP_SHIFT;

                if (scaled > 16'd255)
                    thermal16_to_gray8 = 8'd255;
                else
                    thermal16_to_gray8 = scaled[7:0];
            end
        end
    endfunction

    // =========================================================================
    // SPI receiver
    // =========================================================================
logic [15:0] rx_word_debug;

assign rx_word_debug = {shift_reg_current_word[14:0], video_mosi};


    always_ff @(posedge video_sck or negedge rst_n) begin
        if (!rst_n) begin
            shift_reg_current_word  <= 16'd0;
            bit_cnt                 <= 4'd0;
            word_cnt                <= '0;
    
            frame_active   <= 1'b0;
            capture_enable <= 1'b0;

            pix_valid      <= 1'b0;
            pix_addr       <= '0;
            pix_data       <= 8'd0;
            frame_done     <= 1'b0;
        end 
        else begin
            pix_valid  <= 1'b0;
            frame_done <= 1'b0;

            if (video_csb) begin     //chip not selected
                shift_reg_current_word   <= 16'd0;
                bit_cnt        <= 4'd0;
                word_cnt       <= '0;
                frame_active   <= 1'b0;
                capture_enable <= 1'b0;
            end 
            else begin

                if (!frame_active) begin  //to indicate that the record of new frame is starting
                    frame_active   <= 1'b1;
                    capture_enable <= wr_allow;  //At the beginning of frame,`wr_allow` is copied into `capture_enable`
                                                 //So the decision is made just once at the start of the frame
                                                 //to avoid that changes of wr_allow affects frame’s storage

                    shift_reg_current_word <= {15'd0, video_mosi}; //first bit loaded into the shift register
                    bit_cnt      <= 4'd1;
                    word_cnt     <= '0;
                end 
                else begin

                    shift_reg_current_word <= {shift_reg_current_word[14:0], video_mosi};

                    if (bit_cnt == 4'd15) begin
                        bit_cnt <= 4'd0;

                        if (capture_enable && (word_cnt < FRAME_PIX)) begin
                            pix_valid <= 1'b1;
                            pix_addr  <= word_cnt[ADDR_BITS-1:0]; //save the received pixel at the address corresponding to the number of the received word

                            // Must use concatenation because `shift_reg_current_word` would be updated at the end of the loop
                            //pix_data <= thermal16_to_gray8({shift_reg_current_word[14:0], video_mosi});
                            //pix_data <= rx_word_debug[15:8];
                            //pix_data <= word_cnt[7:0];
                            pix_data <= rx_word_debug[7:0];
                        end

                        if (word_cnt == TOTAL_WORDS - 1) begin   //a new frame can start
                            frame_done   <= capture_enable;  //After received all the TOTAL_WORDS, set frame_done = 1 only if that frame must be saved
                            word_cnt     <= '0;
                            frame_active <= 1'b0;
                        end 
                        else begin
                            word_cnt <= word_cnt + 1'b1;
                        end

                    end 
                    else begin
                        bit_cnt <= bit_cnt + 1'b1;
                    end
                end
            end
        end
    end

endmodule

//valutare l'insrimento di frame_completed in casi in cui CS rimane basso anche dopo che il frame è completato