// ============================================================================
// MODULE: hdmi_top
// DESCRIPTION: Configurable top-level for HDMI output.
// CLOCK NOTE: Based on the board clock, requires a clk_pixel and a clk_tmds(= 5*clk_pixel)
// On the Tang Nano 9K, these clocks must be generated by an rPLL module.
// ============================================================================

module hdmi_top #( 
    // Horizontal parameters (Pixel)   | ACTIVE | FRONT | SYNC | BACK |
    parameter int H_ACTIVE   = 640,  
    parameter int H_FRONT    = 16, 
    parameter int H_SYNC     = 96,
    parameter int H_BACK     = 48,
    parameter int H_TOTAL = H_ACTIVE + H_FRONT + H_SYNC + H_BACK,   //800

    // Vertical Parameters (Lines)     | ACTIVE | FRONT | SYNC | BACK |    
    parameter int V_ACTIVE   = 480,
    parameter int V_FRONT    = 10,
    parameter int V_SYNC     = 2,
    parameter int V_BACK     = 33,
    parameter int V_TOTAL = V_ACTIVE + V_FRONT + V_SYNC + V_BACK,   //525

    // Polarity
    parameter bit H_SYNC_POL = 1'b0,
    parameter bit V_SYNC_POL = 1'b0,

    // Needed bits to correct count pixels
    parameter int H_BITS = $clog2(H_TOTAL),
    parameter int V_BITS = $clog2(V_TOTAL)
)(
    input  logic rst_n,       // Asynchronous reset active low
    input  logic clk_27MHz,   // Board clock
   
    
    // OV5640 signals
    input  logic       ov_pclk,
    input  logic       ov_vsync,
    input  logic       ov_href,
    input  logic [7:0] ov_data,

    output logic       ov_reset_n,
    output logic       ov_pwdn,

    inout  wire        ov_scl,
    inout  wire        ov_sda,
    
    // Differential outputs (On the Tang Nano these are mapped to the TLVDS/LVCMOS33 pins)
    output logic tmds_clk_p,  output logic tmds_clk_n,
    output logic tmds_d0_p,   output logic tmds_d0_n,  // Blue
    output logic tmds_d1_p,   output logic tmds_d1_n,  // Green
    output logic tmds_d2_p,   output logic tmds_d2_n   // Red
);

    // --- Internal signals ---
    logic clk_pixel;          // Pixel_clk
    logic clk_tmds;           // TMDS clock 5x 
    logic [H_BITS-1:0] cx;    //counter x
    logic [V_BITS-1:0] cy;    //counter y
    logic hsync, vsync, vde;
    logic [7:0] red, green, blue;
    logic [9:0] tmds_r, tmds_g, tmds_b;
    
    localparam int VIS_W         = 160;
    localparam int VIS_H         = 120;
    localparam int VIS_FRAME_PIX = VIS_W * VIS_H;
    localparam int VIS_ADDR_BITS = $clog2(VIS_FRAME_PIX);

    logic [VIS_ADDR_BITS-1:0] vis_rd_addr;
    logic [7:0] vis_rd_pixel;

    logic vis_rd_req;
    logic vis_rd_valid;

    logic vis_frame_available;
    logic vis_writing_allowed;
    logic vis_camera_initialized;

    logic        hdmi_frame_start;

    assign hdmi_frame_start = (cx == '0) && (cy == '0);  //is the rd_swap_point

    // --- Clock stage ---
    Gowin_rPLL PLL(
        .clkout(clk_tmds),  //fast clock for serializer
        .reset(~rst_n),
        .clkin(clk_27MHz)
    );

    CLKDIV #(
    .DIV_MODE("5"),
    .GSREN("false")
    ) clk_div_5 (
    .CLKOUT(clk_pixel),   //pixel clock
    .HCLKIN(clk_tmds),
    .RESETN(rst_n),
    .CALIB(1'b0)
    );


// 1. Sincronisms Generator (Timings)    
video_timing #(
        .H_ACTIVE   (H_ACTIVE),
        .H_FRONT    (H_FRONT),
        .H_SYNC     (H_SYNC),
        .H_BACK     (H_BACK),
        .H_TOTAL    (H_TOTAL),
        .H_SYNC_POL (H_SYNC_POL),
        .H_BITS     (H_BITS),

        .V_ACTIVE   (V_ACTIVE),
        .V_FRONT    (V_FRONT),
        .V_SYNC     (V_SYNC),
        .V_BACK     (V_BACK),
        .V_TOTAL    (V_TOTAL),
        .V_SYNC_POL (V_SYNC_POL),
        .V_BITS     (V_BITS)
    ) timing_inst (
        .clk   (clk_pixel),
        .rst_n (rst_n),
        .cx    (cx),
        .cy    (cy),
        .hsync (hsync),
        .vsync (vsync),
        .vde   (vde)
    );


// ============================================================================
// 2. VIS camera manager
// ============================================================================
ov5640_visible_manager #(
    .IMG_W      (VIS_W),
    .IMG_H      (VIS_H),
    .FRAME_PIX  (VIS_FRAME_PIX),
    .ADDR_BITS  (VIS_ADDR_BITS)
) visible_camera_inst (
    .rst_n             (rst_n),
    .sys_clk           (clk_27MHz),

    .ov_pclk           (ov_pclk),
    .ov_vsync          (ov_vsync),
    .ov_href           (ov_href),
    .ov_data           (ov_data),

    .ov_reset_n        (ov_reset_n),  //different reset required for camera configuration
    .ov_pwdn           (ov_pwdn),

    .ov_scl            (ov_scl),
    .ov_sda            (ov_sda),

    .rd_clk            (clk_pixel),
    .rd_swap_point     (hdmi_frame_start),
    .rd_req            (vis_rd_req),
    .rd_addr           (vis_rd_addr),

    .rd_pixel          (vis_rd_pixel),
    .rd_valid          (vis_rd_valid),

    .camera_initialized(vis_camera_initialized),
    .frame_available   (vis_frame_available),
    .writing_allowed   (vis_writing_allowed)
);


// ============================================================================
// VIS camera image renderer
// ============================================================================

visible_hdmi_renderer_rgb332 #(
    .H_ACTIVE  (H_ACTIVE),
    .V_ACTIVE  (V_ACTIVE),
    .H_BITS    (H_BITS),
    .V_BITS    (V_BITS),

    .IMG_W     (VIS_W),
    .IMG_H     (VIS_H),
    .SCALE     (4),

    .FRAME_PIX (VIS_FRAME_PIX),
    .ADDR_BITS (VIS_ADDR_BITS)
) visible_renderer_inst (
    .clk_pixel (clk_pixel),
    .rst_n     (rst_n),

    .cx        (cx),
    .cy        (cy),
    .vde       (vde),

    .rd_req    (vis_rd_req),
    .rd_addr   (vis_rd_addr),
    .rd_pixel  (vis_rd_pixel),
    .rd_valid  (vis_rd_valid),

    .red       (red),
    .green     (green),
    .blue      (blue)
);

// =========================================================================
// 3. TMDS ENCODER + SERIALIZER
// =========================================================================

    // --- Pipeline alignment delay (2 cycles) ---
    logic [1:0] hsync_d, vsync_d, vde_d_top;

    always_ff @(posedge clk_pixel or negedge rst_n) begin
    if (!rst_n) begin
        hsync_d   <= 2'b00;
        vsync_d   <= 2'b00;
        vde_d_top <= 2'b00;
    end
    else begin
        hsync_d   <= {hsync_d[0], hsync};
        vsync_d   <= {vsync_d[0], vsync};
        vde_d_top <= {vde_d_top[0], vde};
    end
    end

    //Encoder TMDS (3 channels)
    // The BLU channel (D0) carries HSYNC and VSYNC during blanking (vde=0)
    
    tmds_encoder enc_b (
        .clk      (clk_pixel),
        .rst_n    (rst_n),
        .data_in  (blue),
        .ctrl     ({vsync_d[1], hsync_d[1]}),
        .vde      (vde_d_top[1]),
        .tmds_out (tmds_b)
    );

        tmds_encoder enc_g (
        .clk      (clk_pixel),
        .rst_n    (rst_n),
        .data_in  (green),
        .ctrl     (2'b00),
        .vde      (vde_d_top[1]),
        .tmds_out (tmds_g)
    );

        tmds_encoder enc_r (
        .clk      (clk_pixel),
        .rst_n    (rst_n),
        .data_in  (red),
        .ctrl     (2'b00),
        .vde      (vde_d_top[1]),
        .tmds_out (tmds_r)
    );

    // Serializer 10:1 (Serialization of the clock needed to compensate the delays introduced by the serialiser)
    logic s_clk, s_d0, s_d1, s_d2;

    serializer_10to1 ser_b   (.rst_n(rst_n), .clk_pixel(clk_pixel), .clk_tmds(clk_tmds), .data_in(tmds_b),     .serial_out(s_d0));
    serializer_10to1 ser_g   (.rst_n(rst_n), .clk_pixel(clk_pixel), .clk_tmds(clk_tmds), .data_in(tmds_g),     .serial_out(s_d1));
    serializer_10to1 ser_r   (.rst_n(rst_n), .clk_pixel(clk_pixel), .clk_tmds(clk_tmds), .data_in(tmds_r),     .serial_out(s_d2));
    serializer_10to1 ser_clk (.rst_n(rst_n), .clk_pixel(clk_pixel), .clk_tmds(clk_tmds), .data_in(10'b1111100000), .serial_out(s_clk));

    // The ELVDS_OBUF primitive is required to generate real differential hardware
    ELVDS_OBUF obuf_d0 (
    .I (s_d0),
    .O (tmds_d0_p),
    .OB(tmds_d0_n)
    );

    ELVDS_OBUF obuf_d1 (
    .I (s_d1),
    .O (tmds_d1_p),
    .OB(tmds_d1_n)
    );

    ELVDS_OBUF obuf_d2 (
    .I (s_d2),
    .O (tmds_d2_p),
    .OB(tmds_d2_n)
    );

    ELVDS_OBUF obuf_clk (
    .I (s_clk),
    .O (tmds_clk_p),
    .OB(tmds_clk_n)
    );

endmodule
