// ============================================================================
// MODULE: double_framebuffer_gowin_sdp
// DESCRIPTION: Double framebuffer using two Gowin_SDP RAM IPs.
//
// RAM0 and RAM1 are used as ping-pong buffers.
// The buffer swap is performed only at rd_swap_point.
//
// Write side:
// - clocked by VIGIL80 video_sck or OV5640 ov_pclk;
// - writes incoming camera pixels;
// - writes only complete frames into the selected bank.
//
// Read side:
// - clocked by HDMI clk_pixel;
// - provides pixels to the HDMI renderer;
// - changes the displayed bank only at the start of an HDMI frame.
//
// IMPORTANT:
// Gowin_SDP RAM has synchronous read access.
// After a read request, rd_data becomes available one rd_clk cycle later.
// rd_valid indicates when the output data is valid.
//
// A single toggle signal, completed_toggle_wr, crosses from the camera clock
// domain to the HDMI clock domain.
// The toggle has two meanings:
// - a change in value indicates that a new complete frame is available;
// - the current value identifies the framebuffer that has been completed..
// ============================================================================
module double_framebuffer_gowin_sdp #(
    parameter int FRAME_PIX = 160 * 120,
    parameter int ADDR_BITS = $clog2(FRAME_PIX)
)(
    input  logic rst_n,

    // ========================================================================
    // Write side - camera domain
    // ========================================================================

    input  logic                 wr_clk,       // Clock generated by the camera
    input  logic                 wr_valid,     // High when one pixel must be written
    input  logic [ADDR_BITS-1:0] wr_addr,      // Address of the camera pixel
    input  logic [7:0]           wr_data,      // RGB332 pixel
    input  logic                 wr_frame_done,// High when a complete frame has been received

    output logic                 wr_allow,     // Permission sent to camera capture:
                                               // 1: next frame can be stored
                                               // 0: incoming frame must be discarded
                                               // because the available bank is still
                                               // displayed by HDMI

    // ========================================================================
    // Read side - HDMI domain
    // ========================================================================

    input  logic                 rd_clk,        // HDMI pixel clock
    input  logic                 rd_swap_point, // High at the start of an HDMI frame
    input  logic                 rd_req,        // Pixel read request
    input  logic [ADDR_BITS-1:0] rd_addr,       // Pixel address requested by HDMI

    output logic [7:0]           rd_data,       // RGB332 pixel read from RAM
    output logic                 rd_valid,      // High when rd_data is valid

    output logic                 frame_available
                                                // Debug/status signal:
                                                // high after the first complete
                                                // camera frame has arrived
);

    // ========================================================================
    // Bank control
    // ========================================================================

    logic wr_bank; // Buffer currently written by the camera:
                   // 0: write RAM0
                   // 1: write RAM1

    logic rd_bank; // Buffer currently read by HDMI:
                   // 0: read RAM0
                   // 1: read RAM1

    // At reset:
    // - HDMI reads RAM0;
    // - camera writes RAM1.
    //
    // This avoids a read/write collision immediately after reset.

    // completed_toggle_wr is updated after every complete camera frame.
    //
    // The signal performs two functions:
    // 1. a change in its value signals a newly completed frame;
    // 2. its value identifies the completed framebuffer.
    //
    // RAM1 complete -> completed_toggle_wr = 1
    // RAM0 complete -> completed_toggle_wr = 0

    logic completed_toggle_wr;

    // ========================================================================
    // Synchronize rd_bank from HDMI/read clock domain to camera/write domain
    // ========================================================================
    //
    // rd_bank is generated in the rd_clk domain but is used in the wr_clk
    // domain to calculate wr_allow.
    //
    // Since rd_clk and wr_clk are asynchronous, rd_bank may change close to
    // a wr_clk edge and violate the setup/hold time of the first flip-flop.
    //
    // The two flip-flop synchronizer provides a stable copy of rd_bank in the
    // camera clock domain:
    //
    // rd_bank -> rd_bank_wr_meta -> rd_bank_wr_sync
    // ========================================================================

    logic rd_bank_wr_meta; // First synchronizer FF, may become metastable
    logic rd_bank_wr_sync; // Second synchronizer FF, safe in wr_clk domain

    always_ff @(posedge wr_clk or negedge rst_n) begin
        if (!rst_n) begin
            rd_bank_wr_meta <= 1'b0;
            rd_bank_wr_sync <= 1'b0;
        end
        else begin
            rd_bank_wr_meta <= rd_bank;
            rd_bank_wr_sync <= rd_bank_wr_meta;
        end
    end

    // The camera may write only if the selected write bank is not the bank
    // currently displayed by HDMI.
    assign wr_allow = (wr_bank != rd_bank_wr_sync);

    // ========================================================================
    // Write-side bank update
    // ========================================================================
    //
    // wr_bank changes only after a complete frame has been written.
    //
    // completed_toggle_wr receives the value of the bank that has just been
    // completed. Therefore the signal identifies the completed bank and also
    // changes value at every valid frame completion.
    //
    // After completing one framebuffer, the camera selects the other bank.
    // If the other bank is still displayed by HDMI, wr_allow becomes zero and
    // the capture module discards incoming frames until HDMI releases it.
    // ========================================================================

    always_ff @(posedge wr_clk or negedge rst_n) begin
        if (!rst_n) begin
            wr_bank             <= 1'b1; // After reset, write RAM1
            completed_toggle_wr <= 1'b0;
        end
        else if (wr_frame_done && wr_allow) begin

            // wr_bank identifies the bank that has just been completed.
            //
            // Assigning wr_bank to completed_toggle_wr:
            // - signals the arrival of a complete frame;
            // - transfers the completed bank identifier to the read domain.
            completed_toggle_wr <= wr_bank;

            // Select the other framebuffer for the next writable frame.
            wr_bank <= ~wr_bank;
        end
    end

    // ========================================================================
    // Synchronize completed-frame event into HDMI/read clock domain
    // ========================================================================
    //
    // completed_toggle_wr is asynchronous with respect to rd_clk.
    // Two flip-flops synchronize the toggle into the HDMI clock domain:
    //
    // completed_toggle_wr
    //        ->
    // completed_toggle_rd_meta
    //        ->
    // completed_toggle_rd_sync
    //
    // A complete frame is detected when completed_toggle_rd_sync differs from
    // completed_toggle_rd_last.
    // ========================================================================

    logic completed_toggle_rd_meta;
    logic completed_toggle_rd_sync;
    logic completed_toggle_rd_last;

    // Indicates that one complete framebuffer is ready to be displayed,
    // but the swap is pending because HDMI is still displaying the current
    // framebuffer.
    logic pending_valid_rd;

    // Identifies which framebuffer is ready to be displayed.
    logic pending_bank_rd;

    always_ff @(posedge rd_clk or negedge rst_n) begin
        if (!rst_n) begin
            completed_toggle_rd_meta <= 1'b0;
            completed_toggle_rd_sync <= 1'b0;
            completed_toggle_rd_last <= 1'b0;

            pending_valid_rd <= 1'b0;
            pending_bank_rd  <= 1'b0;

            rd_bank         <= 1'b0; // After reset, read RAM0
            frame_available <= 1'b0;
        end
        else begin

            // Two-step synchronization of the completed-frame toggle.
            completed_toggle_rd_meta <= completed_toggle_wr;
            completed_toggle_rd_sync <= completed_toggle_rd_meta;

            // Swap the displayed framebuffer only at the beginning of an HDMI
            // frame and only if a complete camera frame is pending.
            //
            // This prevents tearing because rd_bank never changes in the middle
            // of an HDMI frame.
            if (rd_swap_point && pending_valid_rd) begin
                rd_bank          <= pending_bank_rd;
                pending_valid_rd <= 1'b0;
            end

            // Detect a newly completed camera frame.
            // The synchronized toggle value is also the completed bank number.
            //
            // This block is intentionally placed after the swap block.
            // If a swap and a new completed frame occur during the same rd_clk
            // cycle, the older pending frame is displayed and the newly
            // completed frame remains pending for the next HDMI frame.
            if (completed_toggle_rd_sync != completed_toggle_rd_last) begin
                completed_toggle_rd_last <= completed_toggle_rd_sync;

                pending_bank_rd  <= completed_toggle_rd_sync;
                pending_valid_rd <= 1'b1;

                // Status signal: once a complete frame has arrived,
                // frame_available remains high until reset.
                frame_available <= 1'b1;
            end
        end
    end

    // ========================================================================
    // RAM write and read enables
    // ========================================================================

    logic ram0_wr_en;
    logic ram1_wr_en;
    logic ram0_rd_en;
    logic ram1_rd_en;

    // The capture module samples wr_allow at the beginning of a camera frame
    // and generates wr_valid only when that complete frame is authorized.
    //
    // Therefore the RAM write enables depend on wr_valid and wr_bank.
    // wr_allow is not checked again for every pixel, avoiding interruption of
    // an already authorized frame if rd_bank changes asynchronously.
    assign ram0_wr_en = wr_valid && (wr_bank == 1'b0);
    assign ram1_wr_en = wr_valid && (wr_bank == 1'b1);

    // Only the framebuffer selected by rd_bank receives the HDMI read request.
    assign ram0_rd_en = rd_req && (rd_bank == 1'b0);
    assign ram1_rd_en = rd_req && (rd_bank == 1'b1);

    // ========================================================================
    // RAM outputs
    // ========================================================================

    logic [7:0] ram0_dout;
    logic [7:0] ram1_dout;

    // Gowin_SDP read output is synchronous.
    //
    // The selected bank and the read-request signal are delayed by one rd_clk
    // cycle so they remain aligned with the corresponding RAM output.
    logic rd_bank_d;
    logic rd_req_d;

    always_ff @(posedge rd_clk or negedge rst_n) begin
        if (!rst_n) begin
            rd_bank_d <= 1'b0;
            rd_req_d  <= 1'b0;
        end
        else begin
            // If a pixel is requested during the current cycle, the output
            // becomes valid during the next rd_clk cycle.
            rd_req_d <= rd_req;

            // Record which RAM was selected for the current read request.
            // The delayed value selects the correct synchronous RAM output.
            if (rd_req) begin
                rd_bank_d <= rd_bank;
            end
        end
    end

    // rd_valid is asserted one cycle after rd_req.
    assign rd_valid = rd_req_d;

    // Select the RAM output corresponding to the delayed read-bank value.
    always_comb begin
        if (rd_bank_d == 1'b0)
            rd_data = ram0_dout;
        else
            rd_data = ram1_dout;
    end

    // ========================================================================
    // Gowin SDP RAM 0
    //
    // Port A: camera write port
    // Port B: HDMI read port
    // ========================================================================

    Gowin_SDP ram0 (
        .dout   (ram0_dout),     // Output [7:0]

        // Write port
        .clka   (wr_clk),
        .cea    (ram0_wr_en),
        .reseta (~rst_n),        // RAM reset active high
        .ada    (wr_addr),
        .din    (wr_data),

        // Read port
        .clkb   (rd_clk),
        .ceb    (ram0_rd_en),
        .resetb (~rst_n),        // RAM reset active high
        .oce    (1'b1),
        .adb    (rd_addr)
    );

    // ========================================================================
    // Gowin SDP RAM 1
    //
    // Port A: camera write port
    // Port B: HDMI read port
    // ========================================================================

    Gowin_SDP ram1 (
        .dout   (ram1_dout),     // Output [7:0]

        // Write port
        .clka   (wr_clk),
        .cea    (ram1_wr_en),
        .reseta (~rst_n),        // RAM reset active high
        .ada    (wr_addr),
        .din    (wr_data),

        // Read port
        .clkb   (rd_clk),
        .ceb    (ram1_rd_en),
        .resetb (~rst_n),        // RAM reset active high
        .oce    (1'b1),
        .adb    (rd_addr)
    );

endmodule