// ============================================================================
// MODULE: ov5640_dvp_rgb565_capture
// DESCRIPTION: Receives an OV5640 parallel RGB565 stream.
//
// Camera signals:
// - cam_pclk: pixel/byte clock generated by camera
// - cam_vsync: frame synchronization
// - cam_href: high while valid bytes of a line are transmitted
// - cam_data: 8-bit parallel data
//
// RGB565 uses two camera-clock cycles per pixel.
// The complete RGB565 pixel is converted to RGB332 and written to the
// double framebuffer.
//
// Each frame is either completely saved or completely discarded.
// wr_allow is sampled only at the beginning of the frame.
// ============================================================================

module ov5640_dvp_rgb565_capture #(
    parameter int IMG_W      = 160,
    parameter int IMG_H      = 120,
    parameter int FRAME_PIX  = IMG_W * IMG_H,
    parameter int ADDR_BITS  = $clog2(FRAME_PIX),

    parameter bit VSYNC_ACTIVE = 1'b1,  //Specifies which cam_vsync level should be considered active
    parameter bit HREF_ACTIVE  = 1'b1   //Specifies which cam_href level should be considered active
)(
    input  logic rst_n,
    input  logic capture_ready,    //high when the camera configuration is completed

    input  logic       cam_pclk,
    input  logic       cam_vsync,
    input  logic       cam_href,
    input  logic [7:0] cam_data,

    input  logic wr_allow,   //used to not overwrite the frame that HDMI is reading ( 1: save frame; 0: discard frame )

    output logic pix_valid,  //high when the pixel is converted and ready to be saved in frambuffer
    output logic [ADDR_BITS-1:0] pix_addr,
    output logic [7:0] pix_data,
    output logic frame_done  //high after the arrival of FRAME_PIX pixels
);

    logic vsync_is_active;
    logic href_is_active;

    assign vsync_is_active = (cam_vsync == VSYNC_ACTIVE);
    assign href_is_active  = (cam_href  == HREF_ACTIVE);

    logic vsync_d;     //VSYNC value from the previous cycle

    logic frame_active;    //0: No frames currently being captured: 1: frame in capture
    logic capture_enable;  //useful for preventing wr_allow change while saving

    // 0: waiting for first RGB565 byte
    // 1: waiting for second RGB565 byte
    logic byte_phase;

    logic [7:0] first_byte;  //to record 1st byte

    localparam int PIX_CNT_BITS = $clog2(FRAME_PIX + 1);    //se FRAME_PIX fosse una potenza di 2, il contatore non potrebbe rappresentare FRAME_PIX.
    logic [PIX_CNT_BITS-1:0] pixel_count;

    // =========================================================================
    // RGB565 -> RGB332
    //
    // RGB565:
    // [15:11] = red
    // [10:5]  = green
    // [4:0]   = blue
    //
    // RGB332:
    // [7:5] = rgb565[15:13]
    // [4:2] = rgb565[10:8]
    // [1:0] = rgb565[4:3]
    // =========================================================================

    function automatic logic [7:0] rgb565_to_rgb332(   //No LUT required, just a selection of bits
        input logic [15:0] rgb565
    );
        begin
            rgb565_to_rgb332 = {
                rgb565[15:13],
                rgb565[10:8],
                rgb565[4:3]
            };
        end
    endfunction

    // =========================================================================
    // DVP receiver
    // =========================================================================

    always_ff @(posedge cam_pclk or negedge rst_n) begin
        if (!rst_n) begin
            vsync_d       <= 1'b0;

            frame_active  <= 1'b0;
            capture_enable <= 1'b0;

            byte_phase    <= 1'b0;
            first_byte    <= 8'd0;
            pixel_count   <= '0;

            pix_valid     <= 1'b0;
            pix_addr      <= '0;
            pix_data      <= 8'd0;
            frame_done    <= 1'b0;
        end
        else begin
            pix_valid  <= 1'b0;
            frame_done <= 1'b0;

            vsync_d <= vsync_is_active;

            // =================================================================
            // Camera not initialized yet
            // =================================================================

            if (!capture_ready) begin
                frame_active   <= 1'b0;
                capture_enable <= 1'b0;
                byte_phase     <= 1'b0;
                pixel_count    <= '0;
            end

            // =================================================================
            // VSYNC active: frame boundary/blanking. 
            // We use VSYNC to indicate that the record of new frame is starting
            // =================================================================

            else if (vsync_is_active) begin
            
//                if (!vsync_d && frame_active) begin  // if VSYNC has just become active and we had a frame being captured...
// //                  Signal completion only if exactly FRAME_PIX pixels
// //                  were captured and this frame was enabled.
//                    if (capture_enable && (pixel_count == FRAME_PIX)) begin
//                        frame_done <= 1'b1;
//                    end
//                end

                frame_active   <= 1'b0;
                capture_enable <= 1'b0;

                byte_phase  <= 1'b0;
                pixel_count <= '0;
            end

            // =================================================================
            // Active frame area
            // =================================================================

            else begin

                // First non-VSYNC clock starts a new frame.
                // The first time HREF becomes active after VSYNC:
                // -> the frame is considered to have started;
                // -> wr_allow is sampled;
                // -> the counter resets to zero;
                // -> the module aligns to the first RGB565 byte.
                if (!frame_active && href_is_active) begin
                    frame_active   <= 1'b1;
                    capture_enable <= wr_allow;

                    byte_phase  <= 1'b0;
                    pixel_count <= '0;
                end

                // Reset byte alignment at every line boundary.
                if (!href_is_active) begin
                    byte_phase <= 1'b0;
                end

                // Receive RGB565 bytes only while HREF is active.
                else begin
                    if (!byte_phase) begin
                        first_byte <= cam_data;
                        byte_phase <= 1'b1;
                    end
                    else begin
                        byte_phase <= 1'b0;

                        // One complete RGB565 pixel is now available:
                        // {first_byte, cam_data}
                        if (capture_enable &&
                            (pixel_count < FRAME_PIX)) begin
                            pix_valid <= 1'b1;
                            pix_addr  <= pixel_count[ADDR_BITS-1:0];
                            pix_data  <= rgb565_to_rgb332({first_byte, cam_data});
                            //pix_data <= rgb565_to_rgb332({cam_data, first_byte});

                            if (pixel_count == FRAME_PIX - 1) begin
                                frame_done <= 1'b1;
                            end
                        end

                        if (pixel_count < FRAME_PIX) begin
                            pixel_count <= pixel_count + 1'b1;
                        end
                    end
                end
            end
        end
    end

endmodule